version: '2'
services:

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3001"
    environment:
      DB_USERNAME: root
      DB_NAME: megan
      DB_PORT: 3307
      DB_HOST: mysql

  mysql:
    image: "mysql:latest"
    environment:
      MYSQL_DATABASE: megan
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
