# version: '2'

# services:

#   mysql-db:
#     image: "mysql:latest"
#     environment:
#       MYSQL_DATABASE: root
#       MYSQL_USER: root
#       MYSQL_PASSWORD: root
#     ports:
#       - "3307:3306"
#     # volumes:
#     #   - .:/db

#   api:
#     build: .
#     environment:
#       DB_USERNAME: root
#       DB_NAME: root
#       DB_HOST: mysql-db
#       DB_PORT: 3307
#       NODE_ENV: "development"
#     ports:
#       - "8001:8001"
#     depends_on:
#       - mysql-db

version: '2'
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3001"
    environment:
      DB_USERNAME: root
      DB_NAME: root
      DB_PORT: 3307
      DB_HOST: mysql



  mysql:
    image: "mysql:latest"
    environment:
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
